Domino. Needs testing
igorbat/Bolyarichs_mathtour_platform pull request #15
Opened 2023-07-15 11:22 UTC by GrafGeometr

Domino game implemented. Source code is in the /domino folder.

2023-07-21 10:41 UTC, igorbat requested changes

2023-07-21 10:41 UTC, igorbat commented on domino/main.py
> +def reset():
Пока это оставим, но вообще введение пустой функции - зачем..?

Правило бойскаута, опять же, нарушается.

2023-07-21 10:41 UTC, igorbat commented on domino/main.py
> +def reset():
1. Правило бойскаутов.

“Всегда оставляйте лагерь чище, чем он был до вас” — это отличнейшее правило, по которому стоит жить. Если вы нашли мусор на земле, вы убираете его, вне зависимости от того, кто его оставил. Это одно из правил скаутов. Тоже самое должно применяться и в программировании. Как перефразировал это правило Роберт С. Мартин: “Оставь свой код лучше, чем он был до тебя”. Если мы встретим какой-то трудный для чтения участок кода, написанный кем-то другим, и потратили время на его понимание, давайте сделаем его хотя бы немного лучше.

2023-07-21 10:41 UTC, igorbat commented on domino/main.py
> +# @bot.command(name='register', help='зарегистрировать команду: школа, класс или целиком название')
правило бойскаута. Давай удалим

2023-07-21 10:41 UTC, igorbat commented on domino/player_cache.py
> +# DB_NAME = "C:\\KovalenkoDB\\marathon.txt"
правило бойскаута. Давай удалим

2023-07-21 10:41 UTC, igorbat commented on domino/solution_cache.py
> +        # cursor.execute("DROP TABLE solutions;")
правило бойскаута. Давай удалим

2023-07-21 10:41 UTC, igorbat commented on domino/solution_cache.py
> +        return (True, ans)
давай добавим перевод строки. Лучше бы каждый файл завершался на пустую строку

2023-07-21 10:41 UTC, igorbat commented on domino/task_cache.py
> +# DB_NAME = "C:\\KovalenkoDB\\marathon.txt"
правило бойскаута. Давай удалим

2023-07-21 10:41 UTC, igorbat commented on domino/util.py
> +def generate_html_bonuses(solutions, tasks, players):
правило бойскаута. Давай удалим

2023-07-21 10:41 UTC, igorbat commented on domino/main.py
> +async def super_res(ctx):
правило бойскаута. Давай удалим.  generate_html_bonuses нет же : )

2023-07-22 11:44 UTC, igorbat requested changes

2023-07-22 11:44 UTC, igorbat commented on domino/main.py
> +
вот эту строку давай удалим. В индустрии - 2 строки между функциями, 1 строка между методами. Тут 3, нехорошо.

2023-07-23 10:17 UTC, igorbat approved these changes

2023-07-23 10:17 UTC, merged

2023-07-23 10:19 UTC, GrafGeometr commented on domino/main.py
> +# @bot.command(name='register', help='зарегистрировать команду: школа, класс или целиком название')
Done

2023-07-23 10:19 UTC, GrafGeometr commented on domino/player_cache.py
> +# DB_NAME = "C:\\KovalenkoDB\\marathon.txt"
Done

2023-07-23 10:19 UTC, GrafGeometr commented on domino/solution_cache.py
> +        # cursor.execute("DROP TABLE solutions;")
Done

2023-07-23 10:19 UTC, GrafGeometr commented on domino/solution_cache.py
> +        return (True, ans)
Done

2023-07-23 10:20 UTC, GrafGeometr commented on domino/task_cache.py
> +# DB_NAME = "C:\\KovalenkoDB\\marathon.txt"
Done

2023-07-23 10:20 UTC, GrafGeometr commented on domino/util.py
> +def generate_html_bonuses(solutions, tasks, players):
Done

2023-07-23 10:20 UTC, GrafGeometr commented on domino/main.py
> +async def super_res(ctx):
Done

2023-07-23 10:20 UTC, GrafGeometr commented on domino/main.py
> +
Done